name: Build React Native App

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: 30.0.3

    - name: Build Android
      run: |
        cd android
        ./gradlew assembleRelease

    - name: Upload Android build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: android-build
        path: android/app/build/outputs/apk/release/app-release.apk

  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install CocoaPods
      run: |
        cd ios
        pod install

    - name: Build iOS
      run: |
        xcodebuild -workspace ios/YourAppName.xcworkspace -scheme YourAppName -sdk iphoneos -configuration Release archive -archivePath $PWD/build/YourAppName.xcarchive

    - name: Export iOS build artifacts
      run: |
        xcodebuild -exportArchive -archivePath $PWD/build/YourAppName.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $PWD/build/YourAppName

    - name: Upload iOS build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ios-build
        path: build/YourAppName/*.ipa
