name: Build React Native App

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '18'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install Android SDK
      uses: android-actions/setup-android@v3

    - name: Build Android
      run: |
        cd android
        ./gradlew assembleRelease

    - name: Upload Android build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Skyline-android-${{ github.run_number }}
        path: android/app/build/outputs/apk/release/app-release.apk

  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install CocoaPods
      run: |
        cd ios
        pod install

    - name: Build iOS
      run: |
        xcodebuild -workspace ios/Skyline.xcworkspace -scheme Skyline -sdk iphoneos -configuration Release archive -archivePath $PWD/build/Skyline.xcarchive

    - name: Export iOS build artifacts
      run: |
        xcodebuild -exportArchive -archivePath $PWD/build/Skyline.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $PWD/build/Skyline

    - name: Upload iOS build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Skyline-ios-${{ github.run_number }}
        path: build/Skyline/*.ipa
