name: Build and Deploy to Cloud Run

on:
  push:
    paths:
      - 'game-replay/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        docker build \
          -t ghcr.io/${{ github.repository }}/replay:latest \
          ./game-replay

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository }}/replay:latest

    - name: Push Docker image to Google Container Registry
      run: |
        docker tag ghcr.io/${{ github.repository }}/replay:latest gcr.io/$GCP_PROJECT_ID/replay:latest
        docker push gcr.io/$GCP_PROJECT_ID/replay:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy replay \
          --image gcr.io/$GCP_PROJECT_ID/replay:latest \
          --region us-central1 \
          --platform managed \
          --service-account ${{ secrets.CLOUD_RUN_SA }} \
          --allow-unauthenticated \
          --set-env-vars ENDPOINT_ID=${{ secrets.ENDPOINT_ID }},PROJECT_NAME=${{ secrets.PROJECT_NAME }},PROJECT_ID=${{ secrets.PROJECT_ID }}

    - name: Verify deployment
      run: |
        gcloud run services describe replay --region us-central1 --platform managed
