name: Deploy Firebase Functions

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Firebase CLI
      run: |
        curl -sL https://firebase.tools | bash
        firebase --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r functions/get-recent-games/requirements.txt

    - name: Authenticate with Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
      run: firebase projects:list

    - name: Deploy Firebase Functions
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FB_SA }}
      run: firebase deploy --only functions
