name: Deploy to Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'functions/get-recent-games/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.PROJECT_ID }}/get-recent-games

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy get-recent-games \
          --image gcr.io/${{ secrets.PROJECT_ID }}/get-recent-games \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
          --set-env-vars BIGQUERY_DATASET="baseball_custom_dataset",BIGQUERY_TABLE=${{ secrets.BIGQUERY_PLAY_TABLE }}
